wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - "80"
    - 8080:80
  working_dir: /var/www/html
  volumes:
   - .:/var/www/html/wp-content/themes/development
   - test/fixtures/functions.php:/var/www/html/wp-content/themes/development/functions.php
   - test/fixtures/index.php:/var/www/html/wp-content/themes/development/index.php
   - test/fixtures/style.css:/var/www/html/wp-content/themes/development/style.css

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example